# Generated by Django 4.0.5 on 2022-07-24 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selectvideo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='tags',
            field=models.ManyToManyField(related_name='+', to='selectvideo.attributes'),
        ),
    ]
