# Generated by Django 4.0.5 on 2022-08-24 13:12

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('selectvideo', '0002_alter_title_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='desc',
            field=models.TextField(default='No description is available for this title', verbose_name='description'),
        ),
        migrations.AddField(
            model_name='title',
            name='tumbnail',
            field=models.ImageField(default=pathlib.PurePosixPath('/home/ndaniels/media/thumbnails'), upload_to='thumbnail/'),
        ),
    ]
