# Generated by Django 4.0.5 on 2022-08-24 13:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('selectvideo', '0003_title_desc_title_tumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
